FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["MeetingService.API/MeetingService.API.csproj", "MeetingService.API/"]
COPY ["MeetingService.Application/MeetingService.Application.csproj", "MeetingService.Application/"]
COPY ["MeetingService.Domain/MeetingService.Domain.csproj", "MeetingService.Domain/"]
COPY ["MeetingService.Infrastructure/MeetingService.Infrastructure.csproj", "MeetingService.Infrastructure/"]

RUN dotnet restore "MeetingService.API/MeetingService.API.csproj"

COPY . .

RUN dotnet build "MeetingService.API/MeetingService.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MeetingService.API/MeetingService.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MeetingService.API.dll"]
