services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka-network
    command: |
      bash -c '
      sed -i "/KAFKA_ZOOKEEPER_CONNECT/d" /etc/confluent/docker/configure
      /etc/confluent/docker/configure
      if [ ! -f /var/lib/kafka/data/meta.properties ]; then
        kafka-storage format --ignore-formatted -t $$CLUSTER_ID -c /etc/kafka/server.properties
      fi
      /etc/confluent/docker/run
      '
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "TlumeetDB1*"
      ACCEPT_EULA: "Y"
    ports:
      - "14333:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - kafka-network

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: ["--bind_ip_all"]
    volumes:
      - mongo-data:/data/db
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  gateway:
    build:
      context: ./ApiGateway
    container_name: gateway
    ports:
      - "5555:8080"
    environment:
      - Jwt__Key=2f45c598186d199fcef6dd3e81d9d7ff
      - Jwt__Issuer=TLUMeet
      - Jwt__Audience=TLUMeet
    depends_on:
      - authservice
      - meetingservice
      - notiservice
      - user-service
    networks:
      - kafka-network

  authservice:
    build:
        context: ./Services/AuthService
    container_name: authservice
    ports:
      - "8081:8080"
    environment:
      KAFKA_BROKER: kafka:29092
      ConnectionStrings__AuthDB: Server=sqlserver;Database=AuthDB;User=sa;Password=TlumeetDB1*;TrustServerCertificate=True;
    depends_on:
      kafka:
        condition: service_healthy
      sqlserver:
        condition: service_started
    networks:
      - kafka-network

  meetingservice:
    build:
      context: ./Services/MeetingService
    container_name: meetingservice
    ports:
      - "8083:8080"
    environment:
      KAFKA_BROKER: kafka:29092
      ConnectionStrings__DefaultConnection: Server=sqlserver;Database=MeetingDB;User=sa;Password=TlumeetDB1*;TrustServerCertificate=True;
    depends_on:
      kafka:
        condition: service_healthy
      sqlserver:
        condition: service_started
    networks:
      - kafka-network

  notiservice:
    build:
        context: ./Services/NotificationService
    container_name: notiservice
    ports:
      - "8082:8080"
    environment:
      KAFKA_BROKER: kafka:29092
      ConnectionStrings__DefaultConnection: Server=sqlserver;Database=NotificationDB;User=sa;Password=TlumeetDB1*;TrustServerCertificate=True;
    depends_on:
      kafka:
        condition: service_healthy
      sqlserver:
        condition: service_started
    networks:
      - kafka-network

  kowl:
    image: quay.io/cloudhut/kowl:latest
    container_name: kowl
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: kafka:29092
    networks:
      - kafka-network

  user-service:
    build:
      context: ./Services/user-service
    container_name: user-service
    ports:
      - "3001:8080"
    environment:
      - MONGODB_URI=mongodb://root:root@mongodb:27017/user_db?authSource=admin
      - KAFKA_BROKERS=kafka:29092
      - PORT=8080
    depends_on:
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - kafka-network


networks:
  kafka-network:
    driver: bridge

volumes:
  kafka-data:
  sql-data:
  mongo-data: